// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetStatusStatusGetData, GetStatusStatusGetResponses, HealthzHealthzGetData, HealthzHealthzGetResponses, PostMinimizeMinimizePostData, PostMinimizeMinimizePostResponses, PostRestartRestartPostData, PostRestartRestartPostResponses, PostRestoreRestorePostData, PostRestoreRestorePostResponses, PostStartStartPostData, PostStartStartPostResponses, PostStopStopPostData, PostStopStopPostResponses } from './types.gen';
import { zGetStatusStatusGetData, zGetStatusStatusGetResponse, zHealthzHealthzGetData, zPostMinimizeMinimizePostData, zPostMinimizeMinimizePostResponse, zPostRestartRestartPostData, zPostRestartRestartPostResponse, zPostRestoreRestorePostData, zPostRestoreRestorePostResponse, zPostStartStartPostData, zPostStartStartPostResponse, zPostStopStopPostData, zPostStopStopPostResponse } from './zod.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Healthz
 *
 * Liveness probe: returns 200 as long as the manager process is alive.
 */
export const healthzHealthzGet = <ThrowOnError extends boolean = false>(options?: Options<HealthzHealthzGetData, ThrowOnError>) => (options?.client ?? client).get<HealthzHealthzGetResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zHealthzHealthzGetData.parseAsync(data),
    url: '/healthz',
    ...options
});

/**
 * Get Status
 *
 * Snapshot of the current process state, CPU, idle timers, and counts.
 */
export const getStatusStatusGet = <ThrowOnError extends boolean = false>(options?: Options<GetStatusStatusGetData, ThrowOnError>) => (options?.client ?? client).get<GetStatusStatusGetResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zGetStatusStatusGetData.parseAsync(data),
    responseValidator: async (data) => await zGetStatusStatusGetResponse.parseAsync(data),
    url: '/status',
    ...options
});

/**
 * Post Start
 *
 * Start Quark (or restore it from minimized). Idempotent.
 */
export const postStartStartPost = <ThrowOnError extends boolean = false>(options?: Options<PostStartStartPostData, ThrowOnError>) => (options?.client ?? client).post<PostStartStartPostResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zPostStartStartPostData.parseAsync(data),
    responseValidator: async (data) => await zPostStartStartPostResponse.parseAsync(data),
    url: '/start',
    ...options
});

/**
 * Post Stop
 *
 * Stop Quark and free its process group. Idempotent.
 */
export const postStopStopPost = <ThrowOnError extends boolean = false>(options?: Options<PostStopStopPostData, ThrowOnError>) => (options?.client ?? client).post<PostStopStopPostResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zPostStopStopPostData.parseAsync(data),
    responseValidator: async (data) => await zPostStopStopPostResponse.parseAsync(data),
    url: '/stop',
    ...options
});

/**
 * Post Restart
 *
 * Stop then start. Useful after config changes that need a cold start.
 */
export const postRestartRestartPost = <ThrowOnError extends boolean = false>(options?: Options<PostRestartRestartPostData, ThrowOnError>) => (options?.client ?? client).post<PostRestartRestartPostResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zPostRestartRestartPostData.parseAsync(data),
    responseValidator: async (data) => await zPostRestartRestartPostResponse.parseAsync(data),
    url: '/restart',
    ...options
});

/**
 * Post Minimize
 *
 * Minimize the Quark window (keeps the process alive, throttles CPU).
 */
export const postMinimizeMinimizePost = <ThrowOnError extends boolean = false>(options?: Options<PostMinimizeMinimizePostData, ThrowOnError>) => (options?.client ?? client).post<PostMinimizeMinimizePostResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zPostMinimizeMinimizePostData.parseAsync(data),
    responseValidator: async (data) => await zPostMinimizeMinimizePostResponse.parseAsync(data),
    url: '/minimize',
    ...options
});

/**
 * Post Restore
 *
 * Restore the minimized Quark window.
 */
export const postRestoreRestorePost = <ThrowOnError extends boolean = false>(options?: Options<PostRestoreRestorePostData, ThrowOnError>) => (options?.client ?? client).post<PostRestoreRestorePostResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zPostRestoreRestorePostData.parseAsync(data),
    responseValidator: async (data) => await zPostRestoreRestorePostResponse.parseAsync(data),
    url: '/restore',
    ...options
});
