// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * ActionResult
 */
export type ActionResult = {
    /**
     * Ok
     */
    ok?: boolean;
    /**
     * Status
     */
    status: {
        [key: string]: unknown;
    };
};

export type HealthzHealthzGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/healthz';
};

export type HealthzHealthzGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetStatusStatusGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/status';
};

export type GetStatusStatusGetResponses = {
    /**
     * Response Get Status Status Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetStatusStatusGetResponse = GetStatusStatusGetResponses[keyof GetStatusStatusGetResponses];

export type PostStartStartPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/start';
};

export type PostStartStartPostResponses = {
    /**
     * Successful Response
     */
    200: ActionResult;
};

export type PostStartStartPostResponse = PostStartStartPostResponses[keyof PostStartStartPostResponses];

export type PostStopStopPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/stop';
};

export type PostStopStopPostResponses = {
    /**
     * Successful Response
     */
    200: ActionResult;
};

export type PostStopStopPostResponse = PostStopStopPostResponses[keyof PostStopStopPostResponses];

export type PostRestartRestartPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/restart';
};

export type PostRestartRestartPostResponses = {
    /**
     * Successful Response
     */
    200: ActionResult;
};

export type PostRestartRestartPostResponse = PostRestartRestartPostResponses[keyof PostRestartRestartPostResponses];

export type PostMinimizeMinimizePostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/minimize';
};

export type PostMinimizeMinimizePostResponses = {
    /**
     * Successful Response
     */
    200: ActionResult;
};

export type PostMinimizeMinimizePostResponse = PostMinimizeMinimizePostResponses[keyof PostMinimizeMinimizePostResponses];

export type PostRestoreRestorePostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/restore';
};

export type PostRestoreRestorePostResponses = {
    /**
     * Successful Response
     */
    200: ActionResult;
};

export type PostRestoreRestorePostResponse = PostRestoreRestorePostResponses[keyof PostRestoreRestorePostResponses];
