// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

/**
 * ActionResult
 */
export const zActionResult = z.object({
    ok: z.boolean().optional().default(true),
    status: z.record(z.string(), z.unknown())
});

export const zHealthzHealthzGetData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

export const zGetStatusStatusGetData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Response Get Status Status Get
 *
 * Successful Response
 */
export const zGetStatusStatusGetResponse = z.record(z.string(), z.unknown());

export const zPostStartStartPostData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Successful Response
 */
export const zPostStartStartPostResponse = zActionResult;

export const zPostStopStopPostData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Successful Response
 */
export const zPostStopStopPostResponse = zActionResult;

export const zPostRestartRestartPostData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Successful Response
 */
export const zPostRestartRestartPostResponse = zActionResult;

export const zPostMinimizeMinimizePostData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Successful Response
 */
export const zPostMinimizeMinimizePostResponse = zActionResult;

export const zPostRestoreRestorePostData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Successful Response
 */
export const zPostRestoreRestorePostResponse = zActionResult;
