#!/bin/sh
set -eu

CDP_FORWARD_HOST="${CDP_FORWARD_HOST:-quark-docker}"
CDP_FORWARD_PORT="${CDP_FORWARD_PORT:-9222}"
CDP_FORWARD_LOCAL_PORT="${CDP_FORWARD_LOCAL_PORT:-9222}"

echo "Starting CDP forward: 127.0.0.1:${CDP_FORWARD_LOCAL_PORT} -> ${CDP_FORWARD_HOST}:${CDP_FORWARD_PORT}"

socat TCP-LISTEN:${CDP_FORWARD_LOCAL_PORT},bind=127.0.0.1,reuseaddr,fork TCP:${CDP_FORWARD_HOST}:${CDP_FORWARD_PORT} &

exec deno task start